const ActionsName = {
  LOGIN: 'LOGIN',
  LOGOUT: '',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  FETCH_PROFILE: 'FETCH_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_APP: 'UPDATE_APP',
  FETCH_APP_DATA: 'FETCH_APP_DATA',
};

export default ActionsName;
